services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin123'
      POSTGRES_DB: 'daily-diet'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - $HOME/.volumes/postgres:/var/lib/postgresql